version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: gemeindehaus_backend
    env_file:
      - ./backend/.env   # <- Hier sucht Docker nach den Keys (Supabase URL, Service Key, JWT Passwort etc.)
    ports:
      - "3001:3000"
    restart: always

  bot:
    build: ./bot
    container_name: gemeindehaus_bot
    env_file:
      - ./bot/.env       # <- Hier sucht Docker nach dem (Bot Token, Backend URL etc.)
    depends_on:
      - backend
    restart: always
